---
apiVersion: 1

datasources:

- name: Main
  type: prometheus
  url: http://prometheus:9090  

- name: Database
  type: mysql
  url: mysql:3306
  user: root
  jsonData:
    database: backend_template
  secureJsonData:
    password: OuPfme15oAM1m1S8lqy1PQfxlYFlCnmPzyaloZ1Zw=